### ISSUE TITLE
error in manually running standup command

### ISSUE THREAD

**Issue by robmarlow** [limbrapp/lita-standup#1]
I am getting this stack trace when I try to manually test and run a standup: 

I am telling lita in a DM `standup` and typing `standup` after every question and the last time, it says it will post it to the channel then this happens. 

[2018-10-09 21:56:39 UTC] ERROR: Lita::Handlers::Updates crashed. The exception was:

undefined method `strip' for nil:NilClass

Full backtrace:
/var/bundle/ruby/2.3.0/gems/lita-updates-0.1.1/lib/lita/updates/slack_report.rb:17:in `answer'
/var/bundle/ruby/2.3.0/gems/lita-updates-0.1.1/lib/lita/updates/slack_report.rb:25:in `attachments'
/var/bundle/ruby/2.3.0/gems/lita-updates-0.1.1/lib/lita/updates/slack_report.rb:10:in `call'
/var/bundle/ruby/2.3.0/gems/lita-updates-0.1.1/lib/lita/updates/conversation.rb:66:in `report'
/var/bundle/ruby/2.3.0/gems/lita-updates-0.1.1/lib/lita/updates/conversation.rb:37:in `call'
/var/bundle/ruby/2.3.0/gems/lita-updates-0.1.1/lib/lita/updates/commands/standup.rb:15:in `call'
/var/bundle/ruby/2.3.0/gems/lita-updates-0.1.1/lib/lita/updates/commands/standup.rb:3:in `call'
/var/bundle/ruby/2.3.0/gems/lita-updates-0.1.1/lib/lita/handlers/updates.rb:14:in `block in <class:Updates>'
/var/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/callback.rb:29:in `instance_exec'
/var/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/callback.rb:29:in `call'
/var/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:97:in `dispatch_to_route'
/var/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:82:in `block in dispatch'
/var/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:72:in `map'
/var/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:72:in `dispatch'
/var/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/robot.rb:69:in `block in receive'
/usr/local/lib/ruby/2.3.0/set.rb:306:in `each_key'
/usr/local/lib/ruby/2.3.0/set.rb:306:in `each'
/var/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/robot.rb:66:in `map'
/var/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/robot.rb:66:in `receive'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.8.0/lib/lita/adapters/slack/message_handler.rb:122:in `dispatch_message'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.8.0/lib/lita/adapters/slack/message_handler.rb:159:in `handle_message'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.8.0/lib/lita/adapters/slack/message_handler.rb:18:in `handle'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.8.0/lib/lita/adapters/slack/rtm_connection.rb:100:in `block in receive_message'
/var/bundle/ruby/2.3.0/gems/lita-slack-1.8.0/lib/lita/adapters/slack/event_loop.rb:10:in `block in defer'
/var/bundle/ruby/2.3.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'

**Comment by pat** [comment]
Just pushed a commit that should fix this. Also, does it work with messages other than "standup" for each of the questions?

**Comment by robmarlow** [comment]
can you give me an example? I am really just having a hard time getting lita to post back to slack outside of me interacting with lita by typing standup .... I see in the logs where it says that it is starting a standup with me from a scheduled standup. So it is getting scheduled and executing at the proper time, but lita is not initially posting back. I was able to change the schedule and then lita reports back. So it is the same behavior in that to start a standup, I have to type standup twice and then it ask me the first question. Then I have to continue to type standup for the next question to get prompted.

**Comment by pat** [comment]
Hi Rob

I should have been a bit more verbose in my last message - sorry, it was the very end of my night. Testing out the latest commit can be done with the following code in your lita bot's Gemfile:

```ruby
gem "lita-updates", "~> 0.1.1",
  :git => "https://github.com/limbrapp/lita-updates.git"
```

As for examples of how I'm using this library - the README's screenshots are still accurate. Also, here's the shots from a recent check-in of my own. First, the questions that the bot asks me:

![check_in_questions](https://user-images.githubusercontent.com/4183/46751046-5f015280-ccb1-11e8-856a-a8ec04b95760.png)

And then the generated response in the channel I've configured to receive such things:

![check_in_result](https://user-images.githubusercontent.com/4183/46751057-64f73380-ccb1-11e8-93f3-16c6024b975b.png)

Are you able to share your own screenshots? I'm not quite understanding the problems you're hitting, so seeing this should help me grok the situation a bit better.

**Comment by robmarlow** [comment]
here is where I am running the latest version 
![image](https://user-images.githubusercontent.com/35861815/46827536-6e8aa500-cd5e-11e8-8d72-78799c15356b.png)

Here is the slack interaction:
![image](https://user-images.githubusercontent.com/35861815/46827560-806c4800-cd5e-11e8-91ee-d54d50e1901b.png)

and here is the stack trace
![image](https://user-images.githubusercontent.com/35861815/46827573-8c580a00-cd5e-11e8-9157-aafea94c0704.png)

**Comment by pat** [comment]
It seems your responses aren't making it through to lita-updates - as if they're being filtered out/ignored before they even get to the gem's code. Are you using any other lita-related libraries? And if so, is it possible to test things without them?

**Comment by robmarlow** [comment]
I will setup a test env and report back asap
